FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    git unzip libpq-dev libzip-dev \
 && docker-php-ext-install pdo pdo_pgsql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
COPY .. .

RUN composer install --no-interaction --prefer-dist --no-scripts && \
    php artisan key:generate || true && \
    chown -R www-data:www-data storage bootstrap/cache
